/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.up.cs.cos221;

import java.sql.ResultSet;

import javax.swing.JFrame;

/**
 *
 * @author djjor
 */
public class FilmsPane extends javax.swing.JPanel {
    private DBManeger dbManeger;

    /**
     * Creates new form FilmsPane
     */
    public FilmsPane() {
        initComponents();

        dbManeger = new DBManeger();
        String Cols[]={"title", "description", "release_year", "language", "length", "rental_duration", "rental_rate", "replacement_cost", "rating", "special_features"};
        scrollTable1.formatColumns(Cols);
        initData();
    }

    public void initData(){
        String query = "SELECT title, description, release_year, u20473509_sakila.language.name, length, rental_duration, rental_rate, replacement_cost, rating, special_features FROM u20473509_sakila.film inner join u20473509_sakila.language on u20473509_sakila.film.language_id = u20473509_sakila.language.language_id;";
        int cols = 10;
        scrollTable1.deleteData();
        String[][] data;
        java.sql.ResultSet rs = dbManeger.executeQuery(query);
        try {
            rs.last();
            data = new String[rs.getRow()][cols];
            rs.beforeFirst();
            int i = 0;
            while(rs.next()){
                for (int j = 0; j < cols; j++) {
                    data[i][j] = rs.getString(j+1);
                }
                scrollTable1.addRow(data[i]);
                i++;
            }
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTable1 = new za.ac.up.cs.cos221.ScrollTable();
        jButtonAdd = new javax.swing.JButton();

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        AddFilmPopup dialog = new AddFilmPopup(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private za.ac.up.cs.cos221.ScrollTable scrollTable1;
    // End of variables declaration//GEN-END:variables
}
