/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.up.cs.cos221;

import javax.accessibility.AccessibleContext;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.EventListenerList;
import javax.swing.plaf.ComponentUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author djjor
 */
public class ScrollTable extends javax.swing.JPanel {

    /**
     * Creates new form ScrollTable
     */
    public ScrollTable() {
        initComponents();
    }
    
    public void formatColumns(Object[] cols){
        formatTableCols(jTable, cols);
    }
    public void formatTableCols(JTable table, Object[] cols){
        // //remove table cols
        // for (int i = table.getColumnCount()-1; i >= 0; i--) {
        //     table.removeColumn(table.getColumnModel().getColumn(i));
        // }
        // //add Cols
        // for (int i = 0; i < 4; i++) {
        //     TableColumn c = new TableColumn(i);
        //     c.setHeaderValue(cols[i]);
        //     table.addColumn(c);
        //     table.
        // }

        Object[][] obj = new Object[2][cols.length];
        String[] str = new String[cols.length];
        for (int i = 0; i < cols.length; i++) {
            obj[0][i] = null;
            obj[1][i] = null;

            str[i] = cols[i].toString();
        }

        table.setModel(new javax.swing.table.DefaultTableModel(
            obj,
            str
        ));
    }
    
    public void deleteData(){
        deleteTableData(jTable);
    }
    public void deleteTableData(JTable table){
        //delete all data
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.getDataVector().removeAllElements();
    }
    
    public void addRow(Object[] data){
        addTableRow(jTable, data);
    }
    public void addTableRow(JTable table, Object[] data){
        //add row
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.addRow(data);
    }
    
    //--------------------------------------------------------------------------

    public JScrollPane getjScrollPane() {
        return jScrollPane;
    }

    public void setjScrollPane(JScrollPane jScrollPane) {
        this.jScrollPane = jScrollPane;
    }

    public JTable getjTable() {
        return jTable;
    }

    public void setjTable(JTable jTable) {
        this.jTable = jTable;
    }

    public ComponentUI getUi() {
        return ui;
    }

    public void setUi(ComponentUI ui) {
        this.ui = ui;
    }

    public EventListenerList getListenerList() {
        return listenerList;
    }

    public void setListenerList(EventListenerList listenerList) {
        this.listenerList = listenerList;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }
    
    //--------------------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane.setViewportView(jTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
