/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package za.ac.up.cs.cos221;

import java.sql.ResultSet;

import javax.swing.JOptionPane;

/**
 *
 * @author djjor
 */
public class StaffPane extends javax.swing.JPanel {
    private DBManeger dbManeger;

    /**
     * Creates new form StaffPane
     */
    public StaffPane() {
        initComponents();

        dbManeger = new DBManeger();

        String staffCols[]={"ID","First Name","Last Name","Address", "Address2", "District", "City", "Postal Code", "Phone", "Store"};
        scrollTable1.formatColumns(staffCols);
        initData();
    }

    public void initData(){
        String query = "SELECT staff_id, first_name, last_name, u20473509_sakila.address.address, u20473509_sakila.address.address2, u20473509_sakila.address.district, u20473509_sakila.city.city, u20473509_sakila.address.postal_code, u20473509_sakila.address.phone, store_id as store FROM u20473509_sakila.staff INNER JOIN u20473509_sakila.address on u20473509_sakila.staff.address_id = u20473509_sakila.address.address_id INNER JOIN u20473509_sakila.city on u20473509_sakila.address.city_id = u20473509_sakila.city.city_id;";
        populateTable(query, 10);
    }

    public void populateTable(String query, int cols){
        scrollTable1.deleteData();
        String[][] data;
        java.sql.ResultSet rs = dbManeger.executeQuery(query);
        try {
            rs.last();
            data = new String[rs.getRow()][cols];
            rs.beforeFirst();
            int i = 0;
            while(rs.next()){
                for (int j = 0; j < cols; j++) {
                    data[i][j] = rs.getString(j+1);
                }
                scrollTable1.addRow(data[i]);
                i++;
            }
        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextFieldStaffFName = new javax.swing.JTextField();
        jTextFieldStaffLName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldStaffStore = new javax.swing.JTextField();
        jButtonFilter = new javax.swing.JButton();
        scrollTable1 = new za.ac.up.cs.cos221.ScrollTable();
        jButtonClearFilter = new javax.swing.JButton();

        jLabel3.setText("First Name");

        jLabel1.setText("Last Name");

        jLabel2.setText("Store");

        jTextFieldStaffStore.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldStaffStoreKeyReleased(evt);
            }
        });

        jButtonFilter.setText("Filter");
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });

        jButtonClearFilter.setText("Clear");
        jButtonClearFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldStaffFName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(96, 96, 96))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldStaffLName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldStaffStore, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 357, Short.MAX_VALUE)
                        .addComponent(jButtonClearFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFilter))
                    .addComponent(scrollTable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonFilter)
                        .addComponent(jButtonClearFilter))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStaffStore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStaffLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldStaffFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addComponent(scrollTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldStaffStoreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStaffStoreKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStaffStoreKeyReleased

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        if(jTextFieldStaffFName.getText().isEmpty() && jTextFieldStaffLName.getText().isEmpty() && jTextFieldStaffStore.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter at least one filter");
        }else{
            String fname = jTextFieldStaffFName.getText();
            String lname = jTextFieldStaffLName.getText();
            String store = jTextFieldStaffStore.getText();
            String query = "SELECT staff_id, first_name, last_name, u20473509_sakila.address.address, u20473509_sakila.address.address2, u20473509_sakila.address.district, u20473509_sakila.city.city, u20473509_sakila.address.postal_code, u20473509_sakila.address.phone, store_id as store FROM u20473509_sakila.staff INNER JOIN u20473509_sakila.address on u20473509_sakila.staff.address_id = u20473509_sakila.address.address_id INNER JOIN u20473509_sakila.city on u20473509_sakila.address.city_id = u20473509_sakila.city.city_id WHERE ";
            if(!fname.isEmpty()){
                query += "first_name LIKE '%"+fname+"%'";
            }
            if(!lname.isEmpty()){
                if(!fname.isEmpty()){
                    query += " AND ";
                }
                query += "last_name LIKE '%"+lname+"%'";
            }
            if(!store.isEmpty()){
                if(!fname.isEmpty() || !lname.isEmpty()){
                    query += " AND ";
                }
                query += "store_id LIKE '%"+store+"%'";
            }
            query += ";";
            populateTable(query, 10);
        }
    }//GEN-LAST:event_jButtonFilterActionPerformed

    private void jButtonClearFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearFilterActionPerformed
        jTextFieldStaffFName.setText("");
        jTextFieldStaffLName.setText("");
        jTextFieldStaffStore.setText("");
        initData();
    }//GEN-LAST:event_jButtonClearFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClearFilter;
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldStaffFName;
    private javax.swing.JTextField jTextFieldStaffLName;
    private javax.swing.JTextField jTextFieldStaffStore;
    private za.ac.up.cs.cos221.ScrollTable scrollTable1;
    // End of variables declaration//GEN-END:variables
}
